# KEY CONCEPTS

**LIBRARIES:** Numpy (np) & Pandas (pd)

```

1.  Data Cleaning

*   df.dropna(), df.fillna()
*   df.drop_duplicates()
*   df.replace()

2.  Merging and Reshaping Data

*   pd.merge()
*   df.pivot()
*   df.melt()

3.  Grouping and Aggregation

*   df.groupby()
*   df.agg()
```

## PANDAS EXERCISES (Beginner → Professional)

### 🟢 LEVEL 1: Beginner (Core Data Handling)

- Dataset Creation

Use this sample dataset:
```
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha", "Bilal"],
    "Age": [23, 25, 22, 24, 23],
    "City": ["Karachi", "Lahore", "Karachi", "Islamabad", "Lahore"],
    "Salary": [50000, 60000, 45000, 52000, 58000]
}

df = pd.DataFrame(data)
```

### Exercises

#### 1. Display first 3 rows

In [1]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha", "Bilal"],
    "Age": [23, 25, 22, 24, 23],
    "City": ["Karachi", "Lahore", "Karachi", "Islamabad", "Lahore"],
    "Salary": [50000, 60000, 45000, 52000, 58000]
}

df =pd.DataFrame(data)

df.head(3)

    Name  Age     City  Salary
0    Ali   23  Karachi   50000
1   Sara   25   Lahore   60000
2  Ahmed   22  Karachi   45000

#### 2. Get column names

In [2]:
df.columns

Index(['Name', 'Age', 'City', 'Salary'], dtype='object')

#### 3. Select only "Name" and "Salary"

In [3]:
df[['Name', 'Salary']]

     Name  Salary
0     Ali   50000
1    Sara   60000
2   Ahmed   45000
3  Ayesha   52000
4   Bilal   58000

#### 4. Filter people with Salary > 50000

In [4]:
df[df['Salary'] > 50000]

     Name  Age       City  Salary
1    Sara   25     Lahore   60000
3  Ayesha   24  Islamabad   52000
4   Bilal   23     Lahore   58000

#### 5. Add a new column Bonus = Salary * 0.1

In [5]:
df['Bonus'] = df['Salary'] * 0.1
df

     Name  Age       City  Salary   Bonus
0     Ali   23    Karachi   50000  5000.0
1    Sara   25     Lahore   60000  6000.0
2   Ahmed   22    Karachi   45000  4500.0
3  Ayesha   24  Islamabad   52000  5200.0
4   Bilal   23     Lahore   58000  5800.0

#### 6. Sort by Salary descending

In [6]:
df.sort_values('Salary',ascending=False)

     Name  Age       City  Salary   Bonus
1    Sara   25     Lahore   60000  6000.0
4   Bilal   23     Lahore   58000  5800.0
3  Ayesha   24  Islamabad   52000  5200.0
0     Ali   23    Karachi   50000  5000.0
2   Ahmed   22    Karachi   45000  4500.0

#### 7. Count how many people belong to each city

In [7]:
df['City'].value_counts()

City
Karachi      2
Lahore       2
Islamabad    1
Name: count, dtype: int64

### 🟡 LEVEL 2: Data Cleaning (IMPORTANT 🔥)
Dataset (Dirty Data)
```
data = {
    "Name": ["Ali", "Sara", "Ali", None, "Bilal"],
    "Age": [23, None, 23, 24, 23],
    "City": ["Karachi", "Lahore", "Karachi", "Islamabad", None],
    "Salary": [50000, 60000, 50000, None, 58000]
}
df = pd.DataFrame(data)
```

### Exercises (MANDATORY CONCEPTS)

👉 Goal: Clean dataset completely

#### 1. Identify missing values

In [8]:
data2 = {
    "Name": ["Ali", "Sara", "Ali", None, "Bilal"],
    "Age": [23, None, 23, 24, 23],
    "City": ["Karachi", "Lahore", "Karachi", "Islamabad", None],
    "Salary": [50000, 60000, 50000, None, 58000]
}
df2 = pd.DataFrame(data2)

df2.isna().sum()

Name      1
Age       1
City      1
Salary    1
dtype: int64

#### 2. Remove rows with missing values using:
* `df.dropna()`

In [9]:
df2.dropna()

  Name   Age     City   Salary
0  Ali  23.0  Karachi  50000.0
2  Ali  23.0  Karachi  50000.0

#### 3. Fill missing values:
* `Age → mean`
* `City → "Unknown"`

In [10]:
df2['Age'].fillna(df2['Age'].mean())

0    23.00
1    23.25
2    23.00
3    24.00
4    23.00
Name: Age, dtype: float64

In [11]:
df2['City'].fillna('Unknown')

0      Karachi
1       Lahore
2      Karachi
3    Islamabad
4      Unknown
Name: City, dtype: object

#### 4. Remove duplicate rows:
* `df.drop_duplicates()`

In [12]:
duplicate_values = df2.duplicated()
print(f"Duplicate values in DataFrame: {duplicate_values.sum()}")

Duplicate values in DataFrame: 1

In [13]:
df = df2.drop_duplicates()

In [27]:
df

    Name   Age       City   Salary
0    Ali  23.0    Karachi  50000.0
1   Sara   NaN     Lahore  60000.0
3   None  24.0  Islamabad      NaN
4  Bilal  23.0       None  58000.0

#### 5. Replace "Karachi" with "KHI":
* `df.replace()`

In [14]:
df2.replace("Karachi","KHI")

    Name   Age       City   Salary
0    Ali  23.0        KHI  50000.0
1   Sara   NaN     Lahore  60000.0
2    Ali  23.0        KHI  50000.0
3   None  24.0  Islamabad      NaN
4  Bilal  23.0       None  58000.0

### 🟠 LEVEL 3: Grouping & Aggregation

### Exercises


#### 1. Group by City and calculate:
* `Average Salary`
* `Max Salary`

In [15]:
df2.groupby('City')['Salary'].mean()

City
Islamabad        NaN
Karachi      50000.0
Lahore       60000.0
Name: Salary, dtype: float64

In [16]:
df2.groupby('City')['Salary'].max()

City
Islamabad        NaN
Karachi      50000.0
Lahore       60000.0
Name: Salary, dtype: float64

#### 2. Use:
* `df.groupby()`
* `df.agg()`

In [17]:
df2.agg({'Age':'max', 'Salary':'mean'})

Age          24.0
Salary    54500.0
dtype: float64

#### 3. Find total salary per city

In [18]:
df2.groupby('City')['Salary'].sum()

City
Islamabad         0.0
Karachi      100000.0
Lahore        60000.0
Name: Salary, dtype: float64

#### 4. Count employees per city

In [19]:
df2.groupby('City')['Name'].count()

City
Islamabad    0
Karachi      2
Lahore       1
Name: Name, dtype: int64

#### 5. Find highest paid person in each city

In [20]:
df_clean = df2.dropna(subset=['City', 'Salary'])

df_clean.loc[df_clean.groupby('City')['Salary'].idxmax()]

   Name   Age     City   Salary
0   Ali  23.0  Karachi  50000.0
1  Sara   NaN   Lahore  60000.0

### 🔵 LEVEL 4: Merging & Reshaping Data
Dataset
```
df3 = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Ali", "Sara", "Ahmed"]
})

df4 = pd.DataFrame({
    "EmpID": [1, 2, 4],
    "Salary": [50000, 60000, 70000]
})
```

### Exercises (MANDATORY CONCEPTS)

#### 🔹 Merging

##### 1. Perform inner join using:
* `pd.merge()`

In [21]:
# import pandas as pd

df3 = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Ali", "Sara", "Ahmed"]
})

df4 = pd.DataFrame({
    "EmpID": [1, 2, 4],
    "Salary": [50000, 60000, 70000]
})
# pd.merge(df3, df4, on="EmpID", how="inner") # how="inner" is default
pd.merge(df3, df4, on="EmpID")

   EmpID  Name  Salary
0      1   Ali   50000
1      2  Sara   60000

##### 2. Perform left join

In [22]:
df5 = pd.merge(df3, df4, on="EmpID", how="outer")
df5

   EmpID   Name   Salary
0      1    Ali  50000.0
1      2   Sara  60000.0
2      3  Ahmed      NaN
3      4    NaN  70000.0

##### 3. Identify missing matches

In [23]:
missing_matches = df5[df5['Name'].isna() | df5['Salary'].isna()]
print(f"The missing matches in the merged DataFrame are: \n{missing_matches}")

The missing matches in the merged DataFrame are:
   EmpID   Name   Salary
2      3  Ahmed      NaN
3      4    NaN  70000.0

#### 🔹 Reshaping

##### 4. Create pivot table:
* `df.pivot(index='City', columns='Name', values='Salary')`

In [24]:
df.pivot(index='City', columns='Name', values='Salary')

Name       NaN      Ali    Bilal     Sara
City
NaN        NaN      NaN  58000.0      NaN
Islamabad  NaN      NaN      NaN      NaN
Karachi    NaN  50000.0      NaN      NaN
Lahore     NaN      NaN      NaN  60000.0

##### 5. Convert wide → long format:
* `df.melt()`

In [25]:
df.melt(id_vars=['Name'], var_name='Category', value_name='Value')

     Name Category      Value
0     Ali      Age       23.0
1    Sara      Age        NaN
2    None      Age       24.0
3   Bilal      Age       23.0
4     Ali     City    Karachi
5    Sara     City     Lahore
6    None     City  Islamabad
7   Bilal     City       None
8     Ali   Salary    50000.0
9    Sara   Salary    60000.0
10   None   Salary        NaN
11  Bilal   Salary    58000.0

###  🔴 LEVEL 5: Advanced Data Analysis

### Exercises

#### 1. Create a column:
* `Salary Category (Low, Medium, High)`

In [31]:
df.loc[:,'Salary_Category'] = pd.qcut(df['Salary'], q=3, labels=['Low', 'Medium', 'High'])

In [32]:
df

    Name   Age       City   Salary Salary_Category
0    Ali  23.0    Karachi  50000.0             Low
1   Sara   NaN     Lahore  60000.0            High
3   None  24.0  Islamabad      NaN             NaN
4  Bilal  23.0       None  58000.0          Medium

#### 2. Apply custom function using apply()

In [34]:
df['Age_category'] = df['Age'].apply(lambda x: 'Young' if x < 25 else ('Middle_Aged' if x < 35 else 'Old'))
df

/tmp/ipykernel_6290/936774386.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age_category'] = df['Age'].apply(lambda x: 'Young' if x < 25 else ('Middle_Aged' if x < 35 else 'Old'))

    Name   Age       City   Salary Salary_Category Age_category
0    Ali  23.0    Karachi  50000.0             Low        Young
1   Sara   NaN     Lahore  60000.0            High          Old
3   None  24.0  Islamabad      NaN             NaN        Young
4  Bilal  23.0       None  58000.0          Medium        Young

#### 3. Rank employees by salary

In [35]:
df['Salary_Rank'] = df['Salary'].rank(ascending=False)
df

/tmp/ipykernel_6290/2658610756.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Salary_Rank'] = df['Salary'].rank(ascending=False)

    Name   Age       City   Salary Salary_Category Age_category  Salary_Rank
0    Ali  23.0    Karachi  50000.0             Low        Young          3.0
1   Sara   NaN     Lahore  60000.0            High          Old          1.0
3   None  24.0  Islamabad      NaN             NaN        Young          NaN
4  Bilal  23.0       None  58000.0          Medium        Young          2.0

#### 4. Detect outliers using IQR

In [36]:
# Calculate Q1, Q3, and IQR
Q1 = df['Salary'].quantile(0.25)
Q3 = df['Salary'].quantile(0.75)
IQR = Q3 - Q1

# Define bounds
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Filter outliers
filtered_df = df[(df['Salary'] >= lower_bound) & (df['Salary'] <= upper_bound)]

In [37]:
filtered_df

    Name   Age     City   Salary Salary_Category Age_category  Salary_Rank
0    Ali  23.0  Karachi  50000.0             Low        Young          3.0
1   Sara   NaN   Lahore  60000.0            High          Old          1.0
4  Bilal  23.0     None  58000.0          Medium        Young          2.0

#### 5. Normalize salary column

```
# Min-Max Normalization (Scale to 0-1)
(value - min) / (max - min)
```

In [38]:
# df['column_name'] = (df['column_name'] - df['column_name'].min()) / (df['column_name'].max() - df['column_name'].min())
df['Normalized_Salary'] = (df['Salary'] - df['Salary'].min()) / (df['Salary'].max() - df['Salary'].min())
df

/tmp/ipykernel_6290/1653831910.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Normalized_Salary'] = (df['Salary'] - df['Salary'].min()) / (df['Salary'].max() - df['Salary'].min())

,Name,Age,City,Salary,Salary_Category,Age_category,Salary_Rank,Normalized_Salary
0,Ali,23.0,Karachi,50000.0,Low,Young,3.0,0.0
1,Sara,NaN,Lahore,60000.0,High,Old,1.0,1.0
3,None,24.0,Islamabad,NaN,NaN,Young,NaN,NaN
4,Bilal,23.0,None,58000.0,Medium,Young,2.0,0.8

### ⚫ LEVEL 6: Professional-Level Tasks

#### Real-world Mini Projects

##### 🧩 Task 1: Sales Dataset
* Clean dataset
* Handle missing values
* Group by region
* Calculate revenue

[Solved Task](https://colab.research.google.com/drive/1ydCzzuzdUjDW9L3Ju9ogDkcJ-zIJ-F31?usp=sharing)

##### 🧩 Task 2: HR Analytics
* Remove duplicates
* Analyze attrition
* Salary vs department analysis

[Solved Task](https://colab.research.google.com/drive/1-UYzkJWFyzX0txSdNQtqjf6A6ngkdI11?usp=sharing)

##### 🧩 Task 3: E-commerce
* Top-selling products
* Monthly sales trends
* Customer segmentation

[Solved Task](https://colab.research.google.com/drive/1lP9Z9RIQgLuqyypCaCF500IJgsb1Dokx?usp=sharing)

## NUMPY EXERCISES (Beginner → Professional)

### 🟢 LEVEL 1: Basics

### Exercises

#### 1. Create array of numbers 1–10

#### 2. Reshape into 2x5 matrix

#### 3. Find:
* `Mean`
* `Median`
* `Standard deviation`

#### 4. Indexing:
* `Get first row`
* `Get last column`

### 🟡 LEVEL 2: Array Operations

### Exercises

#### 1. Element-wise addition

#### 2. Multiply arrays

#### 3. Dot product

#### 4. Boolean filtering:
* `Values > 5`

#### 5. Replace values:
* `Replace all values > 5 with 100`

### 🟠 LEVEL 3: Mathematical Operations

### Exercises

#### 1. Apply:
* `np.log(), np.sqrt()`

#### 2. Normalize array

#### 3. Compute correlation between two arrays

#### 4. Generate random dataset:
* `np.random.rand()`

### 🔵 LEVEL 4: Advanced Indexing & Slicing

### Exercises

#### 1. Slice sub-matrix

#### 2. Use fancy indexing

#### 3. Modify specific rows/columns

#### 4. Find indices of values > threshold

### 🔴 LEVEL 5: Linear Algebra (Professional 🔥)

### Exercises

#### 1. Matrix multiplication

#### 2. Determinant

#### 3. Inverse

#### 4. Eigenvalues & eigenvectors

### ⚫ LEVEL 6: Real-world Use Cases

### Exercises

#### 🧩 Task 1: Image Processing
* Convert image to numpy array
* Normalize pixel values

#### 🧩 Task 2: Data Simulation
* Generate dataset (1000 rows)
* Add noise
* Analyze distribution

#### 🧩 Task 3: Performance Optimization
* Compare Python list vs NumPy speed

### COMBINED PANDAS + NUMPY PROJECTS (Coming Next)
* End-to-end Data Science workflows
* Kaggle-style datasets
* ML preprocessing pipelines